### ISSUE TITLE
Character / Zone parsing appears to be broken

### ISSUE THREAD

**Issue by jtcasper** [Aireil/FFLogsViewer#47]
I've tried loading a few characters today, getting an error:
```
15:13:38.280 | ERR | [FFLogsViewer] Network error
	Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'Newtonsoft.Json.Linq.JValue' does not contain a definition for 'rankings'
	   at CallSite.Target(Closure, CallSite, Object)
	   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
	   at CallSite.Target(Closure, CallSite, Object)
	   at FFLogsViewer.CharData.ParseZone(Object zone) in D:\a\FFLogsViewer\FFLogsViewer\FFLogsViewer\CharData.cs:line 396
	   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
	   at FFLogsViewer.CharData.<FetchLogs>b__21_0() in D:\a\FFLogsViewer\FFLogsViewer\FFLogsViewer\CharData.cs:line 209
```

**Comment by Aireil** [comment]
FF Logs' API appears to have some issues with some zones, I've pushed a fixed so it doesn't completely errors out.
It should be available in a few minutes, thanks for the report.

**Comment by Aireil** [comment]
FF Logs' API has been fixed and the update should avoid that error for that specific issue, so I'm closing this 🫡.
